const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

// Load .env from root
const envPath = path.join(__dirname, '../.env');
if (fs.existsSync(envPath)) {
    dotenv.config({ path: envPath });
} else {
    console.warn('.env file not found, secrets will be empty');
}

const targetPath = path.join(__dirname, '../electron/secrets.ts');

const content = `
// AUTO-GENERATED FILE - DO NOT EDIT
// This file is generated by scripts/generate-secrets.js
// It contains secrets injected during build time.

export const SMTP_SECRETS = {
  user: '${process.env.SMTP_USER || ""}',
  pass: '${process.env.SMTP_PASS || ""}',
  targetEmail: '${process.env.TARGET_EMAIL || ""}'
};
`;

fs.writeFileSync(targetPath, content);
console.log('Secrets generated at electron/secrets.ts');
